package flags

const ProfileName string = "profile-name"
const CertificateDirectory string = "certificate-directory"
const CertificatePath string = "certificate-path"
const CertificateArn string = "certificate-arn"
const PrivateKeyPath string = "private-key-path"
const TrustAnchor string = "trust-anchor-arn"
const ProfileArn string = "profile-arn"
const RoleArn string = "role-arn"
const Region string = "region"
const AcmpcaArn string = "acmpca-arn"
const CommonName string = "common-name"
const OrganizationName string = "organization-name"
const OrganizationalUnit string = "organizational-unit"
const RevocationReason string = "revocation-reason"
