name: Build & Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
        
      - name: Run build
        run: go build ./src
      
      - name: Run vet & lint
        run: |
          go vet ./src
          golint ./src
    
      - name: Run testing
        run: cd src && go test -v
    