name: Gitleaks Manual

on:
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download gitleaks
        run: |
          curl -LO https://github.com/zricethezav/gitleaks/releases/download/v8.15.2/gitleaks_8.15.2_linux_x64.tar.gz
          tar zxvf gitleaks_8.15.2_linux_x64.tar.gz
          chmod +x gitleaks
      - name: Scan with gitleaks
        run: ./gitleaks detect --redact