name: Snyk GO 

on:
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:
  
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Add mask
        run: |
          echo "::add-mask::${{ secrets.SNYK_CE_TOKEN }}" 

      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        continue-on-error: true 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif